//! Reports which artifacts (skills/agents/workflows with an `evals/` dir) have
//! accumulated enough real, unacted-on evidence since their last GEPA tune to be worth
//! a tuning pass — an accumulation trigger, not a time trigger. Fired daily by
//! `workflows/gepa-due/scripts/trigger.sh`, but this binary itself does the actual
//! deciding: the trigger script only escalates to opening a Pi session when this prints
//! a non-empty due list, never on a schedule alone.
//!
//! No artifact writes a usage log. Evidence comes directly from real Pi session
//! transcripts under `~/.pi/agent/sessions/`: a `read` tool_call whose `arguments.path`
//! ends with an artifact's own definition path counts as one use. "Since last tune" is a
//! TIME cutoff, not a hash-equality match (a transcript hit carries no `prompt_version`
//! field to match against) — `max(the commit timestamp of this artifact's last
//! definition change, the reviewed_through timestamp this tool last recorded for it in
//! `workflows/gepa-due/state/reviewed.jsonl`)`. See `skills/ai-author/SKILL.md`'s "usage
//! evidence" section for the full rationale.
//!
//! Known, accepted limitation: no reliable way was found to distinguish a parent Pi
//! session from a child agent's own transcript on disk (no marker field, no consistent
//! naming convention across `~/.pi/agent/sessions/*`) — every session file is scanned.
//! This can inflate counts from sub-agent reads; stated rather than solved, same as the
//! incidental-read limitation `ai-author/SKILL.md` already documents.
//!
//! Thresholds are fixed constants, not derived from any research (see
//! `PLAN.md`/`skills/ai-author/TUNING.md`'s history for why): >=15 surviving transcript
//! hits marks an artifact "due". Vote count is no longer a due-trigger — votes can now
//! ONLY be generated by an already-due Reflect pass (see `ai-author/SKILL.md`'s judge
//! protocol), so a vote-count threshold would be circular. `vote_count` is still
//! computed and reported, informational only, same treatment as the frontier count.
//!
//! Reports ONLY the due artifacts — "a checker reports only its failures, never its
//! passes" per `ai-author/SKILL.md`'s own rule. An artifact under the threshold is
//! absent from the output entirely, not listed with a false/no-op verdict. Each entry
//! also carries `cutoff_iso`, the exact instant this run used as "since last tune" for
//! that artifact — `trigger.sh` passes this straight into the dispatched session's
//! kickoff prompt, since the session runs in a fresh worktree that can't see the
//! gitignored `workflows/gepa-due/state/reviewed.jsonl` this cutoff was computed from.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

const USAGE_THRESHOLD: usize = 15;
const KINDS: &[&str] = &["skills", "agents", "workflows"];
const UNIT_SEP: char = '\u{1f}';

struct DueArtifact {
    artifact: String,
    usage_count: usize,
    vote_count: usize,
    reason: String,
    cutoff_iso: String,
}

fn home() -> PathBuf {
    PathBuf::from(std::env::var("HOME").unwrap_or_else(|_| "/".to_string()))
}

fn discover_artifacts(root: &Path) -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    for kind in KINDS {
        let Ok(entries) = fs::read_dir(root.join(kind)) else {
            continue;
        };
        for entry in entries.flatten() {
            let dir = entry.path();
            if !dir.is_dir() || !dir.join("evals").is_dir() {
                continue;
            }
            let name = dir.file_name().and_then(|n| n.to_str()).unwrap_or("");
            out.push((format!("{kind}/{name}"), dir));
        }
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

/// The relative path a `read` tool_call's `arguments.path` is expected to END WITH when
/// an artifact's own definition is being read — a suffix match, not an exact absolute
/// match, because artifacts are read from wherever `install.sh` symlinked them
/// (`~/.agents/skills/...`, observed live in a real transcript), never from a fixed
/// absolute location this tool could predict. Per-kind convention confirmed by listing
/// real directories: skills carry `SKILL.md`; agents carry `<name>.md` nested one level
/// deeper; workflows carry `SKILL.md` (the file an agent actually reads to decide
/// whether to dispatch it — not `<name>.workflow.js`, which `SubagentWorkflow` executes
/// directly and no agent ever "reads" the way a skill/agent definition gets read).
fn definition_path_suffix(kind: &str, name: &str) -> String {
    match kind {
        "agents" => format!("agents/{name}/{name}.md"),
        _ => format!("{kind}/{name}/SKILL.md"),
    }
}

/// Mirrors the `git log` invocation `ai-author/SKILL.md`'s "usage evidence" section
/// documents: the commit of the last change to the artifact's OWN files, excluding its
/// harness and vote history — those change on every run and would make prompt_version
/// churn constantly if included. Returns the full hash (still needed to identify
/// frontier candidates and filter votes) AND that commit's own timestamp as Unix epoch
/// seconds (the "since last modification" cutoff — see module doc).
fn current_version_and_timestamp(root: &Path, artifact_rel: &str) -> Option<(String, i64)> {
    let output = Command::new("git")
        .arg("-C")
        .arg(root)
        .args([
            "log",
            "-1",
            &format!("--format=%H{UNIT_SEP}%cI"),
            "--",
            artifact_rel,
            ":(exclude)**/evals/**",
            ":(exclude)**/votes/**",
        ])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let stdout = String::from_utf8(output.stdout).ok()?;
    let line = stdout.trim();
    let (hash, iso_ts) = line.split_once(UNIT_SEP)?;
    if hash.is_empty() {
        return None;
    }
    let epoch = parse_iso8601_to_epoch_seconds(iso_ts)?;
    Some((hash.to_string(), epoch))
}

/// Howard Hinnant's `days_from_civil` — the standard closed-form conversion from a
/// proleptic Gregorian civil date to a day count relative to the Unix epoch. No date
/// library dependency (this tool stays dependency-free per `tools/`'s own convention);
/// this formula is public domain and widely reused for exactly this reason.
fn days_from_civil(y: i64, m: i64, d: i64) -> i64 {
    let y = if m <= 2 { y - 1 } else { y };
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = y - era * 400;
    let mp = (m + 9) % 12;
    let doy = (153 * mp + 2) / 5 + d - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    era * 146097 + doe - 719468
}

/// Howard Hinnant's `civil_from_days` — the inverse of `days_from_civil`. Needed so the
/// cutoff this tool computes can be reported in the JSON output as a real ISO 8601
/// instant (`trigger.sh` passes it straight into a dispatched session's kickoff prompt,
/// instead of re-deriving the same cutoff formula a second time in bash — the
/// dispatched session runs in a fresh, gitignored-state-file-blind worktree and
/// couldn't recompute `reviewed_through` itself even if it tried).
fn civil_from_days(z: i64) -> (i64, i64, i64) {
    let z = z + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}

/// Formats epoch seconds as `YYYY-MM-DDTHH:MM:SSZ` — always UTC/`Z`, never a numeric
/// offset, so a value this tool writes never hits the offset-parsing branch of
/// `parse_iso8601_to_epoch_seconds` (simpler round-trip, one less thing to get wrong).
fn format_epoch_as_iso8601_utc(epoch: i64) -> String {
    let days = epoch.div_euclid(86400);
    let secs_of_day = epoch.rem_euclid(86400);
    let (y, m, d) = civil_from_days(days);
    let hour = secs_of_day / 3600;
    let minute = (secs_of_day % 3600) / 60;
    let second = secs_of_day % 60;
    format!("{y:04}-{m:02}-{d:02}T{hour:02}:{minute:02}:{second:02}Z")
}

/// Parses `YYYY-MM-DDTHH:MM:SS[.fff][Z|±HH:MM]` (both `git log --format=%cI` and Pi's
/// own session-transcript timestamps use this shape, one with a numeric offset, the
/// other with `Z`) into Unix epoch seconds, so the two can be compared as real instants
/// rather than as strings (a lexicographic compare of `Z` against `-04:00` is not a
/// valid time ordering).
fn parse_iso8601_to_epoch_seconds(s: &str) -> Option<i64> {
    if s.len() < 19 {
        return None;
    }
    let year: i64 = s.get(0..4)?.parse().ok()?;
    let month: i64 = s.get(5..7)?.parse().ok()?;
    let day: i64 = s.get(8..10)?.parse().ok()?;
    let hour: i64 = s.get(11..13)?.parse().ok()?;
    let minute: i64 = s.get(14..16)?.parse().ok()?;
    let second: i64 = s.get(17..19)?.parse().ok()?;

    let mut rest = &s[19..];
    if let Some(after_dot) = rest.strip_prefix('.') {
        let digits_end = after_dot
            .find(|c: char| !c.is_ascii_digit())
            .unwrap_or(after_dot.len());
        rest = &after_dot[digits_end..];
    }
    let offset_seconds: i64 = match rest.chars().next() {
        None | Some('Z') => 0,
        Some(sign_char @ ('+' | '-')) => {
            let sign = if sign_char == '+' { 1 } else { -1 };
            let off = &rest[1..];
            let oh: i64 = off.get(0..2)?.parse().ok()?;
            let om: i64 = if off.len() >= 5 {
                off.get(3..5)?.parse().ok()?
            } else {
                0
            };
            sign * (oh * 3600 + om * 60)
        }
        Some(_) => 0,
    };

    let days = days_from_civil(year, month, day);
    Some(days * 86400 + hour * 3600 + minute * 60 + second - offset_seconds)
}

/// Extracts the raw (still JSON-escaped) string value of `"key":"..."` in one JSON
/// object line/slice. No full JSON parser: this repo's own JSONL data and Pi's own
/// transcript records are flat-enough single-line objects that a scan for the key is
/// sufficient and avoids a dependency. Handles `\"` inside the value; does not unescape
/// `\n` etc. beyond the handful this repo's writers actually produce.
fn extract_json_string_field(line: &str, key: &str) -> Option<String> {
    let needle = format!("\"{key}\"");
    let key_pos = line.find(&needle)?;
    let after_key = &line[key_pos + needle.len()..];
    let colon_pos = after_key.find(':')?;
    let after_colon = after_key[colon_pos + 1..].trim_start();
    let mut chars = after_colon.char_indices();
    let (_, quote) = chars.next()?;
    if quote != '"' {
        return None;
    }
    let mut value = String::new();
    let mut escaped = false;
    for (_, ch) in chars {
        if escaped {
            value.push(match ch {
                'n' => '\n',
                't' => '\t',
                'r' => '\r',
                other => other,
            });
            escaped = false;
            continue;
        }
        match ch {
            '\\' => escaped = true,
            '"' => return Some(value),
            other => value.push(other),
        }
    }
    None
}

/// `current_full_hash` is the artifact's CURRENT full commit hash. A logged vote
/// survives when its own `prompt_version` prefix (whatever abbreviated length it
/// happened to be logged at) is a non-empty prefix of that full hash — the same
/// relationship git itself uses to resolve any abbreviated hash, so two
/// different-length loggings of the same commit always match.
fn count_surviving_votes(artifact_dir: &Path, current_full_hash: &str) -> usize {
    let Ok(content) = fs::read_to_string(artifact_dir.join("votes").join("votes.jsonl")) else {
        return 0;
    };
    let vote_prefix_marker = "prompt_version: ";
    content
        .lines()
        .filter(|line| !line.trim().is_empty())
        .filter(|line| {
            let Some(vote) = extract_json_string_field(line, "vote") else {
                return false;
            };
            let Some(rest) = vote.strip_prefix(vote_prefix_marker) else {
                return false;
            };
            let logged = rest.split('\n').next().unwrap_or("");
            !logged.is_empty() && current_full_hash.starts_with(logged)
        })
        .count()
}

/// Reads `workflows/gepa-due/state/reviewed.jsonl` (gitignored, main-checkout-only,
/// written by `workflows/gepa-due/scripts/trigger.sh` after every dispatched session
/// settles) and returns the LATEST `reviewed_through` epoch-seconds cutoff per
/// artifact. Append-only, one line per dispatch, written in chronological order — the
/// last matching line for an artifact wins. Missing file or missing entry for an
/// artifact is not an error: that artifact simply has no recorded review yet.
fn read_reviewed_through(root: &Path) -> HashMap<String, i64> {
    let mut out = HashMap::new();
    let Ok(content) = fs::read_to_string(root.join("workflows/gepa-due/state/reviewed.jsonl"))
    else {
        return out;
    };
    for line in content.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let Some(artifact) = extract_json_string_field(line, "artifact") else {
            continue;
        };
        let Some(reviewed_through) = extract_json_string_field(line, "reviewed_through") else {
            continue;
        };
        let Some(epoch) = parse_iso8601_to_epoch_seconds(&reviewed_through) else {
            continue;
        };
        out.insert(artifact, epoch);
    }
    out
}

/// Finds every `read` tool_call's `arguments.path` value in one transcript JSONL line.
/// Only lines carrying `"role":"assistant"` are considered: a `read` tool's RESULT (a
/// separate `toolResult`-role line) can echo the same path as file content, and would
/// otherwise be miscounted as an invocation. `"arguments":{"path":"..."` is observed to
/// follow `"name":"read"` immediately in every real transcript record, so the search
/// window after each `"name":"read"` occurrence is bounded rather than unbounded, to
/// avoid picking up an unrelated later `path` key from a different tool call.
fn find_read_hit_paths(line: &str) -> Vec<String> {
    if !line.contains("\"role\":\"assistant\"") {
        return Vec::new();
    }
    let marker = "\"name\":\"read\"";
    let mut hits = Vec::new();
    let mut search_from = 0usize;
    while let Some(rel_pos) = line[search_from..].find(marker) {
        let marker_pos = search_from + rel_pos;
        let after_marker = &line[marker_pos..];
        let window_len = 400.min(after_marker.len());
        if let Some(path_rel) = after_marker[..window_len].find("\"path\"") {
            let path_start = marker_pos + path_rel;
            if let Some(value) = extract_json_string_field(&line[path_start..], "path") {
                hits.push(value);
            }
        }
        search_from = marker_pos + marker.len();
    }
    hits
}

/// Single pass over every session transcript under `sessions_dir` (two levels:
/// `sessions/<cwd-dir>/<file>.jsonl`), counting a `read` hit against whichever
/// artifact's `definition_suffix` the hit path ends with, only when the hit's own
/// timestamp is strictly after that artifact's cutoff. One pass shared across all
/// artifacts rather than one pass per artifact, since re-reading ~1000+ transcript
/// files per artifact would multiply cost for no reason.
fn scan_transcripts(
    sessions_dir: &Path,
    artifacts: &[(String, String)],
    cutoffs: &HashMap<String, i64>,
) -> HashMap<String, usize> {
    let mut counts: HashMap<String, usize> = HashMap::new();
    let Ok(session_subdirs) = fs::read_dir(sessions_dir) else {
        return counts;
    };
    for subdir_entry in session_subdirs.flatten() {
        let subdir = subdir_entry.path();
        if !subdir.is_dir() {
            continue;
        }
        let Ok(files) = fs::read_dir(&subdir) else {
            continue;
        };
        for file_entry in files.flatten() {
            let path = file_entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("jsonl") {
                continue;
            }
            let Ok(content) = fs::read_to_string(&path) else {
                continue;
            };
            for line in content.lines() {
                let hit_paths = find_read_hit_paths(line);
                if hit_paths.is_empty() {
                    continue;
                }
                let Some(ts) = extract_json_string_field(line, "timestamp") else {
                    continue;
                };
                let Some(hit_epoch) = parse_iso8601_to_epoch_seconds(&ts) else {
                    continue;
                };
                for hit_path in &hit_paths {
                    for (artifact, suffix) in artifacts {
                        if !hit_path.ends_with(suffix.as_str()) {
                            continue;
                        }
                        let cutoff = cutoffs.get(artifact).copied().unwrap_or(i64::MIN);
                        if hit_epoch > cutoff {
                            *counts.entry(artifact.clone()).or_insert(0) += 1;
                        }
                    }
                }
            }
        }
    }
    counts
}

fn json_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn render_json(due: &[DueArtifact]) -> String {
    if due.is_empty() {
        return "[]".to_string();
    }
    let entries: Vec<String> = due
        .iter()
        .map(|d| {
            format!(
                "{{\"artifact\":\"{}\",\"usage_count\":{},\"vote_count\":{},\"reason\":\"{}\",\"cutoff_iso\":\"{}\"}}",
                json_escape(&d.artifact),
                d.usage_count,
                d.vote_count,
                json_escape(&d.reason),
                json_escape(&d.cutoff_iso)
            )
        })
        .collect();
    format!("[{}]", entries.join(","))
}

fn main() -> ExitCode {
    let root_arg = std::env::args().nth(1).unwrap_or_else(|| ".".to_string());
    let root = fs::canonicalize(&root_arg).unwrap_or_else(|_| PathBuf::from(&root_arg));
    let sessions_dir = std::env::var("GEPA_DUE_SESSIONS_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| home().join(".pi").join("agent").join("sessions"));

    let discovered = discover_artifacts(&root);
    let reviewed_through = read_reviewed_through(&root);

    // Per-artifact identity (full hash, for votes) and cutoff (for transcript hits),
    // computed once up front so the single transcript scan below can look them up.
    let mut identity: Vec<(String, PathBuf, String)> = Vec::new(); // artifact, dir, full_hash
    let mut suffixes: Vec<(String, String)> = Vec::new(); // artifact, definition_suffix
    let mut cutoffs: HashMap<String, i64> = HashMap::new();

    for (artifact, dir) in &discovered {
        let kind = artifact.split('/').next().unwrap_or("");
        let name = artifact.split('/').nth(1).unwrap_or("");
        let Some((full_hash, commit_epoch)) = current_version_and_timestamp(&root, artifact)
        else {
            // No computable version (not a git repo, or artifact untracked yet) —
            // degrade to "not due" rather than guess; never crash the daily run over
            // one artifact's git history.
            continue;
        };
        let cutoff = reviewed_through
            .get(artifact)
            .copied()
            .map(|rt| rt.max(commit_epoch))
            .unwrap_or(commit_epoch);
        cutoffs.insert(artifact.clone(), cutoff);
        suffixes.push((artifact.clone(), definition_path_suffix(kind, name)));
        identity.push((artifact.clone(), dir.clone(), full_hash));
    }

    let usage_counts = scan_transcripts(&sessions_dir, &suffixes, &cutoffs);

    let mut due = Vec::new();
    for (artifact, dir, full_hash) in &identity {
        let usage_count = usage_counts.get(artifact).copied().unwrap_or(0);
        let vote_count = count_surviving_votes(dir, full_hash);
        if usage_count < USAGE_THRESHOLD {
            continue;
        }
        let cutoff = cutoffs.get(artifact).copied().unwrap_or(0);
        due.push(DueArtifact {
            artifact: artifact.clone(),
            usage_count,
            vote_count,
            reason: format!("usage_count {usage_count} >= {USAGE_THRESHOLD}"),
            cutoff_iso: format_epoch_as_iso8601_utc(cutoff),
        });
    }
    due.sort_by(|a, b| a.artifact.cmp(&b.artifact));

    println!("{}", render_json(&due));
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_json_string_field_finds_simple_value() {
        let line = r#"{"ts":"x","prompt_version":"abc1234","outcome":"success"}"#;
        assert_eq!(
            extract_json_string_field(line, "prompt_version").as_deref(),
            Some("abc1234")
        );
    }

    #[test]
    fn extract_json_string_field_handles_escaped_quotes() {
        let line = r#"{"vote":"prompt_version: abc1234\nsaid \"hello\""}"#;
        assert_eq!(
            extract_json_string_field(line, "vote").as_deref(),
            Some("prompt_version: abc1234\nsaid \"hello\"")
        );
    }

    #[test]
    fn extract_json_string_field_missing_key_is_none() {
        let line = r#"{"ts":"x"}"#;
        assert_eq!(extract_json_string_field(line, "prompt_version"), None);
    }

    #[test]
    fn definition_path_suffix_matches_real_conventions() {
        assert_eq!(definition_path_suffix("skills", "ai-author"), "skills/ai-author/SKILL.md");
        assert_eq!(
            definition_path_suffix("agents", "anchor-verifier"),
            "agents/anchor-verifier/anchor-verifier.md"
        );
        assert_eq!(
            definition_path_suffix("workflows", "research-sweep"),
            "workflows/research-sweep/SKILL.md"
        );
    }

    #[test]
    fn parse_iso8601_handles_z_and_offset_as_the_same_instant() {
        // 2026-08-29T04:30:22Z is the same instant as 2026-08-29T00:30:22-04:00.
        let z = parse_iso8601_to_epoch_seconds("2026-08-29T04:30:22.472Z").unwrap();
        let offset = parse_iso8601_to_epoch_seconds("2026-08-29T00:30:22-04:00").unwrap();
        assert_eq!(z, offset);
    }

    #[test]
    fn parse_iso8601_orders_instants_correctly_across_representations() {
        // A lexicographic string compare of these two would get the ordering wrong
        // ('Z' < '-' is false lexicographically for what should be the earlier instant) —
        // this is exactly why epoch-seconds comparison replaced string prompt_version
        // matching for transcript hits.
        let earlier = parse_iso8601_to_epoch_seconds("2026-08-29T00:00:00-04:00").unwrap();
        let later = parse_iso8601_to_epoch_seconds("2026-08-29T05:00:00Z").unwrap();
        assert!(earlier < later);
    }

    #[test]
    fn parse_iso8601_rejects_too_short_input() {
        assert_eq!(parse_iso8601_to_epoch_seconds("2026-08-29"), None);
    }

    #[test]
    fn format_epoch_as_iso8601_utc_round_trips_through_parse() {
        let original = "2026-08-29T04:30:22Z";
        let epoch = parse_iso8601_to_epoch_seconds(original).unwrap();
        assert_eq!(format_epoch_as_iso8601_utc(epoch), original);
    }

    #[test]
    fn format_epoch_as_iso8601_utc_handles_epoch_zero() {
        assert_eq!(format_epoch_as_iso8601_utc(0), "1970-01-01T00:00:00Z");
    }

    #[test]
    fn find_read_hit_paths_only_counts_assistant_role_read_calls() {
        let assistant_line = r#"{"type":"message","timestamp":"2026-08-29T04:30:22.472Z","message":{"role":"assistant","content":[{"type":"toolCall","name":"read","arguments":{"path":"/Users/x/.agents/skills/ai-author/SKILL.md"}}]}}"#;
        assert_eq!(
            find_read_hit_paths(assistant_line),
            vec!["/Users/x/.agents/skills/ai-author/SKILL.md".to_string()]
        );

        // A toolResult echoing the same path as file content must NOT count.
        let tool_result_line = r#"{"type":"message","message":{"role":"toolResult","content":[{"type":"text","text":"path mentioned: /Users/x/.agents/skills/ai-author/SKILL.md, name read"}]}}"#;
        assert!(find_read_hit_paths(tool_result_line).is_empty());
    }

    #[test]
    fn find_read_hit_paths_ignores_non_read_tool_calls() {
        let line = r#"{"type":"message","timestamp":"2026-08-29T04:30:22.472Z","message":{"role":"assistant","content":[{"type":"toolCall","name":"write","arguments":{"path":"/tmp/x"}}]}}"#;
        assert!(find_read_hit_paths(line).is_empty());
    }

    #[test]
    fn count_surviving_votes_filters_by_vote_prefix() {
        let dir = std::env::temp_dir().join(format!("gepa-due-test-votes-{}", std::process::id()));
        let votes = dir.join("votes");
        fs::create_dir_all(&votes).unwrap();
        fs::write(
            votes.join("votes.jsonl"),
            "{\"vote\":\"prompt_version: aaa\\nsome critique\"}\n\
             {\"vote\":\"prompt_version: bbb\\nother critique\"}\n\
             {\"vote\":\"no prefix at all\"}\n",
        )
        .unwrap();
        assert_eq!(count_surviving_votes(&dir, "aaa"), 1);
        assert_eq!(count_surviving_votes(&dir, "bbb"), 1);
        assert_eq!(count_surviving_votes(&dir, "ccc"), 0);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn count_surviving_votes_matches_across_abbreviation_lengths() {
        let dir =
            std::env::temp_dir().join(format!("gepa-due-test-votes-abbrev-{}", std::process::id()));
        let votes = dir.join("votes");
        fs::create_dir_all(&votes).unwrap();
        fs::write(
            votes.join("votes.jsonl"),
            "{\"vote\":\"prompt_version: 76a831fd\\nshort form\"}\n\
             {\"vote\":\"prompt_version: 76a831fda8\\nlonger form\"}\n\
             {\"vote\":\"prompt_version: deadbeef\\nunrelated commit\"}\n",
        )
        .unwrap();
        let current_full_hash = "76a831fda89d3d78150038c04b7af6726b5312ba";
        assert_eq!(count_surviving_votes(&dir, current_full_hash), 2);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn read_reviewed_through_takes_the_latest_matching_line() {
        let dir = std::env::temp_dir().join(format!("gepa-due-test-state-{}", std::process::id()));
        let state = dir.join("workflows/gepa-due/state");
        fs::create_dir_all(&state).unwrap();
        fs::write(
            state.join("reviewed.jsonl"),
            "{\"artifact\":\"skills/foo\",\"reviewed_through\":\"2026-08-01T00:00:00Z\"}\n\
             {\"artifact\":\"skills/foo\",\"reviewed_through\":\"2026-08-15T00:00:00Z\"}\n\
             {\"artifact\":\"skills/bar\",\"reviewed_through\":\"2026-08-10T00:00:00Z\"}\n",
        )
        .unwrap();
        let out = read_reviewed_through(&dir);
        assert_eq!(
            out.get("skills/foo").copied(),
            parse_iso8601_to_epoch_seconds("2026-08-15T00:00:00Z")
        );
        assert_eq!(
            out.get("skills/bar").copied(),
            parse_iso8601_to_epoch_seconds("2026-08-10T00:00:00Z")
        );
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn read_reviewed_through_missing_file_is_empty() {
        let dir = std::env::temp_dir().join(format!("gepa-due-test-nostate-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        assert!(read_reviewed_through(&dir).is_empty());
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn scan_transcripts_counts_only_hits_after_cutoff() {
        let sessions =
            std::env::temp_dir().join(format!("gepa-due-test-sessions-{}", std::process::id()));
        let subdir = sessions.join("--some-cwd--");
        fs::create_dir_all(&subdir).unwrap();
        let before = r#"{"type":"message","timestamp":"2026-08-01T00:00:00Z","message":{"role":"assistant","content":[{"type":"toolCall","name":"read","arguments":{"path":"/x/skills/foo/SKILL.md"}}]}}"#;
        let after = r#"{"type":"message","timestamp":"2026-08-20T00:00:00Z","message":{"role":"assistant","content":[{"type":"toolCall","name":"read","arguments":{"path":"/x/skills/foo/SKILL.md"}}]}}"#;
        fs::write(subdir.join("s.jsonl"), format!("{before}\n{after}\n")).unwrap();

        let artifacts = vec![("skills/foo".to_string(), "skills/foo/SKILL.md".to_string())];
        let mut cutoffs = HashMap::new();
        cutoffs.insert(
            "skills/foo".to_string(),
            parse_iso8601_to_epoch_seconds("2026-08-10T00:00:00Z").unwrap(),
        );
        let counts = scan_transcripts(&sessions, &artifacts, &cutoffs);
        assert_eq!(counts.get("skills/foo").copied(), Some(1));
        fs::remove_dir_all(&sessions).ok();
    }

    #[test]
    fn discover_artifacts_requires_evals_dir() {
        let dir = std::env::temp_dir().join(format!("gepa-due-test-discover-{}", std::process::id()));
        fs::create_dir_all(dir.join("skills/has-evals/evals")).unwrap();
        fs::create_dir_all(dir.join("skills/no-evals")).unwrap();
        let found = discover_artifacts(&dir);
        let names: Vec<&str> = found.iter().map(|(n, _)| n.as_str()).collect();
        assert!(names.contains(&"skills/has-evals"));
        assert!(!names.contains(&"skills/no-evals"));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn render_json_empty_due_list() {
        assert_eq!(render_json(&[]), "[]");
    }

    #[test]
    fn render_json_one_entry() {
        let due = vec![DueArtifact {
            artifact: "skills/foo".to_string(),
            usage_count: 16,
            vote_count: 0,
            reason: "usage_count 16 >= 15".to_string(),
            cutoff_iso: "2026-08-01T00:00:00Z".to_string(),
        }];
        let rendered = render_json(&due);
        assert!(rendered.contains("\"artifact\":\"skills/foo\""));
        assert!(rendered.contains("\"usage_count\":16"));
        assert!(rendered.contains("\"vote_count\":0"));
        assert!(rendered.contains("\"cutoff_iso\":\"2026-08-01T00:00:00Z\""));
    }
}
